"""dummy_col added

Revision ID: 09d3bb873988
Revises: e4b96a355098
Create Date: 2026-05-22 23:23:06.651019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d3bb873988'
down_revision: Union[str, Sequence[str], None] = 'e4b96a355098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dummy_col', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'dummy_col')
    # ### end Alembic commands ###
